export default function TermsOfService() {
  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '2rem' }}>
      <h1>Terms of Service</h1>
      <p><em>Last Updated: {new Date().toISOString().split('T')[0]}</em></p>

      <h2>Acceptance of Terms</h2>
      <p>
        By accessing and using Türbilder (the "Service"), you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
      </p>

      <h2>Description of Service</h2>
      <p>
        Türbilder is a web application that processes IFC (Industry Foundation Classes) files to generate door view diagrams in SVG format. The Service optionally integrates with Airtable to allow users to upload generated views to their own Airtable workspaces.
      </p>

      <h2>User Responsibilities</h2>
      <h3>IFC Files and Data</h3>
      <ul>
        <li>You are responsible for ensuring you have the right to process and share any IFC files you upload to the Service.</li>
        <li>You acknowledge that all IFC file processing happens locally in your browser and is not transmitted to our servers.</li>
        <li>You are responsible for the accuracy and legality of any data you upload to your Airtable workspace.</li>
      </ul>

      <h3>Airtable Integration</h3>
      <ul>
        <li>You must comply with <a href="https://www.airtable.com/tos" target="_blank" rel="noopener noreferrer">Airtable's Terms of Service</a> when using the Airtable integration.</li>
        <li>You are responsible for managing access to your Airtable workspace and revoking permissions when needed.</li>
        <li>You acknowledge that data uploaded to Airtable is governed by Airtable's terms and privacy policy.</li>
      </ul>

      <h2>Prohibited Uses</h2>
      <p>You agree NOT to:</p>
      <ul>
        <li>Use the Service for any illegal purpose or in violation of any applicable laws</li>
        <li>Attempt to gain unauthorized access to the Service or related systems</li>
        <li>Interfere with or disrupt the Service or servers</li>
        <li>Upload malicious code or files that could harm the Service or other users</li>
        <li>Use the Service to process files you do not have permission to access</li>
      </ul>

      <h2>Intellectual Property</h2>
      <ul>
        <li><strong>Your Content:</strong> You retain all rights to IFC files and door data you process using the Service.</li>
        <li><strong>Generated SVGs:</strong> You own the SVG files generated by the Service based on your IFC data.</li>
        <li><strong>Our Service:</strong> The Service code and functionality are provided under open-source licenses as specified in the repository.</li>
      </ul>

      <h2>Disclaimer of Warranties</h2>
      <p>
        THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO:
      </p>
      <ul>
        <li>Accuracy or completeness of door analysis and SVG generation</li>
        <li>Compatibility with all IFC file formats or versions</li>
        <li>Uninterrupted or error-free operation</li>
        <li>Security of data transmission or storage</li>
      </ul>

      <h2>Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR:
      </p>
      <ul>
        <li>Any indirect, incidental, special, or consequential damages</li>
        <li>Loss of data, profits, or business opportunities</li>
        <li>Damages arising from use of or inability to use the Service</li>
        <li>Errors or inaccuracies in generated SVG files</li>
        <li>Unauthorized access to your Airtable workspace by third parties</li>
      </ul>

      <h2>Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless the Service providers from any claims, damages, or expenses arising from:
      </p>
      <ul>
        <li>Your use of the Service</li>
        <li>Your violation of these Terms</li>
        <li>Your violation of any third-party rights</li>
        <li>Unauthorized use of IFC files or data</li>
      </ul>

      <h2>Data and Privacy</h2>
      <p>
        Your use of the Service is also governed by our <a href="/privacy-policy">Privacy Policy</a>. Key points:
      </p>
      <ul>
        <li>IFC files are processed locally in your browser</li>
        <li>Airtable OAuth tokens are stored in encrypted session cookies for up to 8 hours</li>
        <li>We do not store your IFC files or Airtable credentials on our servers</li>
      </ul>

      <h2>Session Expiration</h2>
      <p>
        For security, Airtable authentication sessions automatically expire after 8 hours of inactivity. You will need to reconnect to continue using the Airtable integration.
      </p>

      <h2>Modifications to Service</h2>
      <p>
        We reserve the right to:
      </p>
      <ul>
        <li>Modify or discontinue the Service at any time without notice</li>
        <li>Update these Terms of Service with changes posted on this page</li>
        <li>Refuse service to anyone for any reason</li>
      </ul>

      <h2>Third-Party Services</h2>
      <p>
        The Service integrates with third-party services (Airtable, Vercel) that have their own terms and policies. Your use of these services is subject to their respective terms.
      </p>

      <h2>Governing Law</h2>
      <p>
        These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles.
      </p>

      <h2>Contact</h2>
      <p>
        If you have questions about these Terms of Service, please contact the developers via the repository.
      </p>

      <h2>Severability</h2>
      <p>
        If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.
      </p>
    </div>
  )
}
